services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks: pong-network
    expose:
      - "3308"
    restart: always;

  backend:
    build: ./backend
    container_name: backend
    networks: pong-network
    expose:
      - "3000"
    restart: always;

  mariadb:
    build: ./mariadb
    container_name: mariadb
    networks: pong-network
    env_file:
      - ./secrets/.env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always;

networks:
  pong-network:
