services:
  backend:
    build: ./backend
    env_file:
      - ./backend/secrets/.env
    container_name: pong-backend
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    volumes:
      - frontend-dist:/app/dist
    container_name: pong-frontend

  nginx:
    build: ./nginx
    container_name: pong-nginx
    ports:
      - "443:443"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  frontend-dist:
